import {DEFAULT_STORY_ANALYSIS_MODEL,STORY_ANALYSIS_MODELS,isStoryAnalysisModel,type StoryAnalysisModel} from "./story-analysis-models";

export const XKIRO_STORY_MODELS=STORY_ANALYSIS_MODELS;
export type XKiroStoryModel=StoryAnalysisModel;
export const DEFAULT_XKIRO_STORY_MODEL=DEFAULT_STORY_ANALYSIS_MODEL;

export type XKiroFailureCode="not_configured"|"invalid_model"|"unauthorized"|"rate_limited"|"timeout"|"server_error"|"invalid_response"|"empty_response"|"request_failed";

export class XKiroRequestError extends Error{
  constructor(message:string,public readonly code:XKiroFailureCode,public readonly status?:number){super(message);this.name="XKiroRequestError"}
}

const getBaseUrl=()=>process.env.XKIRO_BASE_URL?.replace(/\/$/,"")||"https://api.xkiro.com/v1";
const getApiKey=()=>process.env.XKIRO_API_KEY?.trim()||"";
const getTimeout=()=>{const value=Number(process.env.XKIRO_ANALYZE_TIMEOUT_MS||90000);return Number.isFinite(value)&&value>0?value:90000};

export function hasXKiro(){return Boolean(getApiKey())}
export function isXKiroStoryModel(value:unknown):value is XKiroStoryModel{return isStoryAnalysisModel(value)}

async function fetchWithTimeout(input:string|URL,init:RequestInit,timeoutMs:number){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(input,{...init,signal:controller.signal})}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new XKiroRequestError(`xKiro request timed out after ${Math.round(timeoutMs/1000)} seconds.`,"timeout",504);throw new XKiroRequestError("xKiro request could not be completed.","request_failed",502)}finally{clearTimeout(timer)}}

export function extractFirstJsonObject(value:string){const cleaned=value.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start===-1||end===-1||end<=start)throw new XKiroRequestError("xKiro returned an invalid structured response.","invalid_response",502);try{return JSON.parse(cleaned.slice(start,end+1))}catch{throw new XKiroRequestError("xKiro returned malformed JSON.","invalid_response",502)}}

function contentText(content:unknown){if(typeof content==="string")return content;if(Array.isArray(content))return content.map((part)=>typeof part==="string"?part:part&&typeof part==="object"&&"text" in part&&typeof (part as {text?:unknown}).text==="string"?(part as {text:string}).text:"").join("");if(content&&typeof content==="object")return JSON.stringify(content);return ""}
function statusError(status:number){if(status===401||status===403)return new XKiroRequestError("xKiro authentication failed. Check the server-side XKIRO_API_KEY.","unauthorized",status);if(status===429)return new XKiroRequestError("xKiro rate limit reached. StoryFrame will try its existing fallback analysis.","rate_limited",status);if(status>=500)return new XKiroRequestError("xKiro is temporarily unavailable. StoryFrame will try its existing fallback analysis.","server_error",status);return new XKiroRequestError(`xKiro request failed with status ${status}.`,"request_failed",status)}

export async function xkiroJsonCompletion(input:{model:StoryAnalysisModel;systemPrompt:string;userPrompt:string;maxTokens?:number;temperature?:number}){const key=getApiKey();if(!key)throw new XKiroRequestError("XKIRO_API_KEY is not configured.","not_configured",503);if(!isStoryAnalysisModel(input.model))throw new XKiroRequestError("Unsupported xKiro story model.","invalid_model",400);const response=await fetchWithTimeout(`${getBaseUrl()}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:input.model,messages:[{role:"system",content:input.systemPrompt},{role:"user",content:input.userPrompt}],temperature:input.temperature??0.15,max_tokens:input.maxTokens??14000,response_format:{type:"json_object"}}),cache:"no-store"},getTimeout());const raw=await response.text();if(!response.ok){console.error("xKiro API error",{status:response.status,body:raw.replace(/\s+/g," ").slice(0,500)});throw statusError(response.status)}let envelope:unknown;try{envelope=JSON.parse(raw)}catch{console.error("xKiro returned non-JSON API envelope",raw.replace(/\s+/g," ").slice(0,500));throw new XKiroRequestError("xKiro returned an invalid API response.","invalid_response",502)}const content=(envelope as {choices?:Array<{message?:{content?:unknown}}>}|null)?.choices?.[0]?.message?.content;const text=contentText(content);if(!text)throw new XKiroRequestError("xKiro returned an empty analysis response.","empty_response",502);return {text,json:extractFirstJsonObject(text)}}

export async function xkiroAnalyzeStory(input:{story:string;visualStyle:string;model:XKiroStoryModel}){const words=input.story.trim().split(/\s+/).filter(Boolean).length;const targetScenes=Math.min(60,Math.max(4,Math.ceil(words/60)));const system=`You are StoryFrame AI, an expert visual story director and storyboard prompt writer. Return STRICT valid JSON only, never markdown or commentary. Preserve source chronology and facts; do not invent major plot events. Output exactly these top-level keys: summary, characters, locations, scenes. characters[] fields: name, role, appearance, outfit, consistencyNotes. locations[] fields: name, architecture, lighting, continuity. scenes[] fields: sourceText, description, characterNames, locationName, cameraShot, cameraAngle, duration, imagePrompt, negativePrompt, continuityNotes. Break the story into meaningful visual beats. Character descriptions must be reusable and consistent. Location descriptions must preserve reusable layout, architecture, props and lighting. imagePrompt must always be in English and standalone usable. Never request captions, subtitles, logos, watermarks or speech bubbles.`;const user=`Visual style: ${input.visualStyle}\nScene budget: approximately ${targetScenes}; actual story beats are more important, maximum 60 scenes.\n\nStory:\n${input.story}`;const result=await xkiroJsonCompletion({model:input.model,systemPrompt:system,userPrompt:user,temperature:0.15,maxTokens:14000});return {raw:result.text,json:result.json,provider:"xkiro",model:input.model}}
