import type {ContinuityStrength,ObjectReference,ProjectVisualBible} from "./types";
import type {AnalyzeChapterResponse,CharacterReference,LocationReference,MangaProject,MangaScene} from "./project-types";
import {deriveSeed} from "./seed";
import {defaultCostume,defaultIdentity,entityCode,normalizeName} from "./project-defaults";

export function mergeCharacterReferences(existing:CharacterReference[],incoming:AnalyzeChapterResponse["characters"],chapterId:string,masterSeed:number){const next=[...existing];const byName=new Set(next.map((item)=>normalizeName(item.name)));for(const candidate of incoming){if(byName.has(normalizeName(candidate.name)))continue;const id=entityCode("CHAR",next.length+1);const now=new Date().toISOString();const outfit=candidate.outfit||candidate.costumeLock?.primaryOutfit||"stable story-appropriate outfit";next.push({id,name:candidate.name,role:candidate.role||"recurring character",visualDescription:candidate.visualDescription,outfit,eyeColor:candidate.eyeColor||candidate.identityLock?.eyeColor||"dark brown",hairColor:candidate.hairColor||candidate.identityLock?.hairColor||"black",keyFeatures:candidate.keyFeatures||[],referencePrompt:candidate.referencePrompt,seedBase:deriveSeed(masterSeed,id),referenceImages:[],identityLock:defaultIdentity({...candidate.identityLock,eyeColor:candidate.eyeColor||candidate.identityLock?.eyeColor,hairColor:candidate.hairColor||candidate.identityLock?.hairColor}),costumeLock:defaultCostume(outfit,candidate.costumeLock),personalityVisuals:candidate.personalityVisuals||"",negativeChanges:["do not change face","do not change hairstyle","do not change age","do not change costume colors","do not change body proportions"],locked:true,states:[{id:"normal",name:"Normal",description:"base established appearance"}],activeStateId:"normal",createdInChapterId:chapterId,updatedAt:now});byName.add(normalizeName(candidate.name))}return next}

export function mergeLocationReferences(existing:LocationReference[],incoming:AnalyzeChapterResponse["locations"],chapterId:string){const next=[...existing];const byName=new Set(next.map((item)=>normalizeName(item.name)));for(const candidate of incoming){if(byName.has(normalizeName(candidate.name)))continue;const now=new Date().toISOString();next.push({id:entityCode("ENV",next.length+1),name:candidate.name,architectureStyle:candidate.architectureStyle,lighting:candidate.lighting,colorPalette:candidate.colorPalette,referencePrompt:candidate.referencePrompt,geometryIdentity:candidate.geometryIdentity||"preserve established layout and silhouette",materials:candidate.materials||"story-appropriate ancient Chinese fantasy materials",importantFeatures:candidate.importantFeatures||[],locked:true,seedOffset:next.length+1,referenceImages:[],createdInChapterId:chapterId,updatedAt:now});byName.add(normalizeName(candidate.name))}return next}

export function mergeObjectReferences(existing:ObjectReference[],incoming:Array<AnalyzeChapterResponse["props"][number]|AnalyzeChapterResponse["vehicles"][number]>,chapterId:string,kind:"prop"|"vehicle"){const next=[...existing];const byName=new Set(next.map((item)=>normalizeName(item.name)));for(const candidate of incoming){if(byName.has(normalizeName(candidate.name)))continue;const isArtifact="kind" in candidate&&candidate.kind==="artifact";const prefix=kind==="vehicle"?"VEHICLE":isArtifact?"ARTIFACT":"PROP";const now=new Date().toISOString();next.push({id:entityCode(prefix,next.length+1),kind:kind==="vehicle"?"vehicle":isArtifact?"artifact":"prop",name:candidate.name,owner:candidate.owner,shape:candidate.shape,size:candidate.size,materials:candidate.materials,colors:candidate.colors,ornamentation:candidate.ornamentation,magicalEffects:candidate.magicalEffects,canonicalPrompt:candidate.canonicalPrompt,locked:true,seedOffset:next.length+1,referenceImages:[],createdInChapterId:chapterId,updatedAt:now});byName.add(normalizeName(candidate.name))}return next}

export function updateVisualBible(base:ProjectVisualBible,incoming?:Partial<ProjectVisualBible>):ProjectVisualBible{if(!incoming)return base;return {...base,...incoming,projectId:base.projectId,masterSeed:base.masterSeed,continuityStrength:base.continuityStrength,visualStyle:{...base.visualStyle,...(incoming.visualStyle||{})},world:{...base.world,...(incoming.world||{})},createdAt:base.createdAt,updatedAt:new Date().toISOString()}}
export function setContinuityStrength(project:MangaProject,strength:ContinuityStrength):MangaProject{return {...project,visualBible:{...project.visualBible,continuityStrength:strength,updatedAt:new Date().toISOString()},updatedAt:new Date().toISOString()}}
export function getPreviousContinuity(project:MangaProject,scene:MangaScene){if(scene.continuityFrom)return project.sceneContinuity.find((item)=>item.sceneId===scene.continuityFrom);const all=project.chapters.flatMap((chapter)=>chapter.scenes);const index=all.findIndex((item)=>item.id===scene.id);const previous=index>0?all[index-1]:undefined;return previous?project.sceneContinuity.find((item)=>item.sceneId===previous.id):undefined}
