/* eslint-disable @typescript-eslint/no-explicit-any */
import type {CharacterCostumeLock,CharacterIdentityLock,ObjectReference,ProjectVisualBible} from "./types";
import type {CharacterReference,LocationReference,MangaChapter,MangaProject,MangaScene} from "./project-types";
import {createMasterSeed,deriveSeed,stableHash} from "./seed";

const MASTER_STYLE="premium cinematic Chinese donghua animation keyframe, semi-realistic anime, highly detailed painterly rendering, beautiful expressive anime faces, realistic cloth folds, intricate ancient Chinese fantasy costume embroidery, cinematic depth, professional composition, atmospheric perspective, rich environment detail, warm natural sunlight, soft golden rim lighting, volumetric illumination, physically believable shadows, subtle bloom, dramatic cloudscape, high-end animated feature film frame";
const NEGATIVE_STYLE="no modern clothing, no modern buildings, no western medieval architecture, no futuristic metallic spaceship, no cyberpunk, no guns, no random hairstyle changes, no face redesign, no costume redesign, no age changes, no random accessory changes, no duplicate main characters, no extra limbs, no malformed hands, no distorted anatomy, no text, no watermark, no logo, no inconsistent architecture";

export function entityCode(prefix:string,index:number){return `${prefix}_${String(index).padStart(3,"0")}`}
export function normalizeName(value:string){return value.trim().toLocaleLowerCase().replace(/\s+/g," ")}
export function hashString(value:string){return (stableHash(value)%9_000_000)+100_000}

export function defaultIdentity(input:Partial<CharacterIdentityLock>={}):CharacterIdentityLock{return {gender:input.gender||"unspecified",apparentAge:input.apparentAge||"young adult",faceShape:input.faceShape||"distinct consistent face",skinTone:input.skinTone||"consistent natural skin tone",eyeColor:input.eyeColor||"dark brown",eyeShape:input.eyeShape||"expressive anime eyes",hairColor:input.hairColor||"black",hairLength:input.hairLength||"medium",hairstyle:input.hairstyle||"story-appropriate cultivation hairstyle",bodyBuild:input.bodyBuild||"slim athletic",heightClass:input.heightClass||"average"}}
export function defaultCostume(outfit:string,input:Partial<CharacterCostumeLock>={}):CharacterCostumeLock{return {primaryOutfit:input.primaryOutfit||outfit||"stable story-appropriate cultivation outfit",primaryColors:input.primaryColors||[],belt:input.belt||"consistent belt",boots:input.boots||"consistent boots",accessories:input.accessories||"preserve established accessories",weapons:input.weapons||[]}}

export function createDefaultVisualBible(projectId:string,storyTitle:string,createdAt:string):ProjectVisualBible{
  return {projectId,storyTitle,masterSeed:createMasterSeed(storyTitle,createdAt),continuityStrength:"strict",visualStyle:{genre:"Xianxia / Donghua",renderStyle:"premium cinematic Chinese donghua, semi-realistic anime",detailLevel:"high",lightingStyle:"warm natural sunlight, soft golden rim lighting, volumetric illumination",colorPalette:["dark navy","mahogany brown","antique gold","cyan spiritual blue","white clouds","warm sunlight"],architectureStyle:"ancient Chinese xianxia architecture with dark carved wood, bronze and antique-gold ornamentation",environmentStyle:"vast seas of clouds, floating mountain temples, spiritual technology, no modern objects",cameraLanguage:"cinematic animated feature framing, strong silhouettes, atmospheric depth, varied lenses and motivated camera angles",aspectRatio:"16:9"},masterStylePrompt:MASTER_STYLE,negativeStylePrompt:NEGATIVE_STYLE,world:{id:"WORLD_001",genre:"ancient Chinese xianxia cultivation civilization",environmentRules:["vast seas of clouds","floating mountain temples","traditional Chinese architecture","spiritual technology","no modern objects"],architecture:{materials:["dark carved wood","bronze","antique gold"],roofStyle:"sweeping layered Chinese tiled roofs",ornamentStyle:"ornate carved cloud, dragon and geometric motifs",energyTechnology:"cyan-blue spiritual cores and flowing qi light"},palette:["dark navy","mahogany brown","antique gold","cyan spiritual blue","white clouds","warm sunlight"],canonicalPrompt:"ancient Chinese xianxia cultivation civilization, vast seas of bright white clouds, floating mountain temples, traditional ornate Chinese architecture, dark carved wood, bronze and antique gold ornamentation, cyan spiritual energy technology, no modern objects",locked:true},createdAt,updatedAt:createdAt};
}

export function createChapter(title="Chapter 1"):MangaChapter{const now=new Date().toISOString();return {id:`chapter-${stableHash(`${title}|${now}`).toString(36)}`,title,story:"",summary:"",scenes:[],createdAt:now,updatedAt:now}}
export function createProject(name="My Manga Project"):MangaProject{const now=new Date().toISOString();const id=`project-${stableHash(`${name}|${now}`).toString(36)}`;const chapter=createChapter();return {id,name,activeChapterId:chapter.id,chapters:[chapter],visualBible:createDefaultVisualBible(id,name,now),characters:[],locations:[],props:[],vehicles:[],sceneContinuity:[],createdAt:now,updatedAt:now}}

function migrateCharacter(raw:any,index:number,bible:ProjectVisualBible,createdAt:string):CharacterReference{const id=String(raw.id||"").startsWith("CHAR_")?raw.id:entityCode("CHAR",index+1);const outfit=raw.outfit||"stable story-appropriate outfit";return {...raw,id,name:raw.name||`Character ${index+1}`,role:raw.role||"recurring character",visualDescription:raw.visualDescription||"stable recurring character identity",outfit,eyeColor:raw.eyeColor||"dark brown",hairColor:raw.hairColor||"black",keyFeatures:raw.keyFeatures||[],referencePrompt:raw.referencePrompt||`${raw.name||`Character ${index+1}`}, stable recurring character identity`,seedBase:raw.seedBase||deriveSeed(bible.masterSeed,id),referenceImages:raw.referenceImages||[],identityLock:defaultIdentity(raw.identityLock),costumeLock:defaultCostume(outfit,raw.costumeLock),personalityVisuals:raw.personalityVisuals||"",negativeChanges:raw.negativeChanges||["do not change face","do not change hairstyle","do not change age","do not change costume colors","do not change body proportions"],locked:raw.locked??true,states:raw.states||[{id:"normal",name:"Normal",description:"base established appearance"}],activeStateId:raw.activeStateId||"normal",createdInChapterId:raw.createdInChapterId||"legacy",updatedAt:raw.updatedAt||createdAt}}
function migrateLocation(raw:any,index:number,bible:ProjectVisualBible,createdAt:string):LocationReference{const id=String(raw.id||"").startsWith("ENV_")?raw.id:entityCode("ENV",index+1);return {...raw,id,name:raw.name||`Location ${index+1}`,architectureStyle:raw.architectureStyle||"stable recurring xianxia architecture",lighting:raw.lighting||"cinematic motivated lighting",colorPalette:raw.colorPalette||bible.visualStyle.colorPalette.join(", "),referencePrompt:raw.referencePrompt||`${raw.name||`Location ${index+1}`}, stable recurring environment`,geometryIdentity:raw.geometryIdentity||"preserve established layout and silhouette",materials:raw.materials||"dark carved wood, stone, bronze and antique gold as appropriate",importantFeatures:raw.importantFeatures||[],locked:raw.locked??true,seedOffset:raw.seedOffset||index+1,referenceImages:raw.referenceImages||[],createdInChapterId:raw.createdInChapterId||"legacy",updatedAt:raw.updatedAt||createdAt}}
function migrateObject(raw:any,index:number,kind:"prop"|"vehicle",createdAt:string):ObjectReference{const artifact=raw.kind==="artifact";const prefix=kind==="vehicle"?"VEHICLE":artifact?"ARTIFACT":"PROP";return {...raw,id:String(raw.id||"").startsWith(prefix+"_")?raw.id:entityCode(prefix,index+1),kind:kind==="vehicle"?"vehicle":artifact?"artifact":"prop",name:raw.name||`${kind} ${index+1}`,shape:raw.shape||"stable recurring shape",size:raw.size||"story-appropriate scale",materials:raw.materials||"story-appropriate materials",colors:raw.colors||[],ornamentation:raw.ornamentation||"consistent ornamentation",magicalEffects:raw.magicalEffects||"none unless established",canonicalPrompt:raw.canonicalPrompt||`${raw.name||kind}, preserve established design`,locked:raw.locked??true,seedOffset:raw.seedOffset||index+1,referenceImages:raw.referenceImages||[],createdInChapterId:raw.createdInChapterId||"legacy",updatedAt:raw.updatedAt||createdAt}}

function migrateScene(raw:any,index:number,bible:ProjectVisualBible,characters:CharacterReference[],locations:LocationReference[]):MangaScene{const sceneNumber=raw.sceneNumber||index+1;const id=String(raw.id||"").startsWith("SCENE_")?raw.id:entityCode("SCENE",sceneNumber);const names=raw.characterNames||[];const locationNames=raw.locationNames||[];return {...raw,id,sceneNumber,title:raw.title||`Scene ${sceneNumber}`,visualCategory:normalizeCategory(raw.visualCategory),sourceText:raw.sourceText||"",description:raw.description||raw.sourceText||"",characterNames:names,characterIds:raw.characterIds||names.map((name:string)=>characters.find((c)=>normalizeName(c.name)===normalizeName(name))?.id).filter(Boolean),locationNames,locationId:raw.locationId||locations.find((l)=>locationNames.some((name:string)=>normalizeName(name)===normalizeName(l.name)))?.id,propIds:raw.propIds||[],vehicleIds:raw.vehicleIds||[],cameraShot:raw.cameraShot||"wide cinematic shot",cameraAngle:raw.cameraAngle||"eye-level",shot:raw.shot||{shotSize:raw.cameraShot||"wide cinematic shot",cameraAngle:raw.cameraAngle||"eye-level",lensFeel:"cinematic natural perspective",composition:"clear focal hierarchy",cameraMovementSuggestion:"subtle cinematic movement"},action:raw.action||raw.description||"",emotion:raw.emotion||"",lightingStyle:raw.lightingStyle||"cinematic motivated lighting",timeOfDay:raw.timeOfDay||"unspecified",weather:raw.weather||"stable",storyState:raw.storyState||raw.description||"",characterStates:raw.characterStates||{},continuityNotes:raw.continuityNotes||"preserve established visual continuity",baseImagePrompt:raw.baseImagePrompt||raw.imagePrompt||"",imagePrompt:raw.imagePrompt||raw.baseImagePrompt||"",narrationScript:raw.narrationScript||raw.sourceText||"",seed:raw.seed||deriveSeed(bible.masterSeed,id,raw.variationIndex||0),variationIndex:raw.variationIndex||0,seedLocked:raw.seedLocked??true,promptLocked:raw.promptLocked??false,status:raw.status||"idle"}}
function normalizeCategory(value:any):any{const map:Record<string,string>={"Establishing Shot":"ESTABLISHING","Action Shot":"ACTION","Crowd Shot":"CROWD","Close-Up Motivation":"CLOSE-UP","Next Generation Training":"MOVEMENT"};return map[value]||value||"ESTABLISHING"}

export function migrateProject(raw:any):MangaProject{const name=raw?.name||"My Manga Project";const createdAt=raw?.createdAt||new Date().toISOString();const id=raw?.id||`project-${stableHash(`${name}|${createdAt}`).toString(36)}`;const defaults=createDefaultVisualBible(id,name,createdAt);const visualBible={...defaults,...(raw?.visualBible||{}),visualStyle:{...defaults.visualStyle,...(raw?.visualBible?.visualStyle||{})},world:{...defaults.world,...(raw?.visualBible?.world||{})},projectId:id};const characters=(raw?.characters||[]).map((item:any,index:number)=>migrateCharacter(item,index,visualBible,createdAt));const locations=(raw?.locations||[]).map((item:any,index:number)=>migrateLocation(item,index,visualBible,createdAt));const props=(raw?.props||[]).map((item:any,index:number)=>migrateObject(item,index,"prop",createdAt));const vehicles=(raw?.vehicles||[]).map((item:any,index:number)=>migrateObject(item,index,"vehicle",createdAt));const chapters=(raw?.chapters?.length?raw.chapters:[createChapter()]).map((chapter:any)=>({...chapter,scenes:(chapter.scenes||[]).map((scene:any,index:number)=>migrateScene(scene,index,visualBible,characters,locations)),createdAt:chapter.createdAt||createdAt,updatedAt:chapter.updatedAt||createdAt}));return {id,name,activeChapterId:raw?.activeChapterId&&chapters.some((c:MangaChapter)=>c.id===raw.activeChapterId)?raw.activeChapterId:chapters[0].id,chapters,visualBible,characters,locations,props,vehicles,sceneContinuity:raw?.sceneContinuity||[],createdAt,updatedAt:raw?.updatedAt||createdAt}}
