import type {ImageProviderCapabilities} from "../image-providers/types";
import type {CharacterReference,LocationReference,MangaProject,MangaScene} from "./project-types";
import type {ContinuityValidationIssue,SceneContinuityRecord} from "./types";
import {promptFingerprint} from "./seed";

const STRICT_LOCK=`STRICT CONTINUITY:\nsame visual universe as previous scenes,\npreserve established character identity,\npreserve exact facial traits,\npreserve hairstyle,\npreserve costume design and colors,\npreserve apparent age and body proportions,\npreserve recurring environment architecture,\npreserve recurring props and vehicle design,\npreserve established material language,\npreserve established color palette,\ndo not redesign previously established visual elements.`;
const norm=(value:string)=>value.trim().toLowerCase().replace(/\s+/g," ");

function characterBlock(character:CharacterReference,stateValue?:string){const identity=character.identityLock;const costume=character.costumeLock;const state=character.states.find((item)=>item.id===stateValue||norm(item.name)===norm(stateValue||""));const stateText=state?`Temporary story-authorized state: ${state.name}: ${state.description}${state.outfitOverride?`; outfit override: ${state.outfitOverride}`:""}${state.visualEffects?.length?`; effects: ${state.visualEffects.join(", ")}`:""}. Base identity remains unchanged.`:`Current story state: ${stateValue||character.activeStateId||"normal"}.`;return `${character.id} — ${character.name} (${character.role}). CANONICAL CHARACTER LOCK: ${character.referencePrompt}. Identity: ${identity.gender}, apparent age ${identity.apparentAge}, ${identity.faceShape}, ${identity.skinTone}, ${identity.eyeShape} ${identity.eyeColor} eyes, ${identity.hairLength} ${identity.hairColor} hair, ${identity.hairstyle}, ${identity.bodyBuild}, height ${identity.heightClass}. Costume: ${costume.primaryOutfit}; colors ${costume.primaryColors.join(", ")||"preserve established colors"}; belt ${costume.belt}; boots ${costume.boots}; accessories ${costume.accessories}; weapons ${costume.weapons.join(", ")||"none established"}. ${character.personalityVisuals}. ${stateText} Negative changes: ${character.negativeChanges.join(", ")}.`}
function locationBlock(location:LocationReference){return `${location.id} — ${location.name}. LOCATION LOCK: ${location.referencePrompt}. Geometry identity: ${location.geometryIdentity}. Architecture: ${location.architectureStyle}. Materials: ${location.materials}. Important features: ${location.importantFeatures.join(", ")}. Lighting identity: ${location.lighting}. Palette: ${location.colorPalette}. Do not redesign this recurring environment.`}
function objectBlock(item:MangaProject["props"][number]){return `${item.id} — ${item.name}. ${item.kind.toUpperCase()} LOCK: ${item.canonicalPrompt}. Shape ${item.shape}; size ${item.size}; materials ${item.materials}; colors ${item.colors.join(", ")}; ornamentation ${item.ornamentation}; magical effects ${item.magicalEffects}; owner ${item.owner||"unassigned"}. Do not redesign.`}
function previousBlock(previous?:SceneContinuityRecord){if(!previous)return "";const s=previous.continuitySummary;return `PREVIOUS SCENE MEMORY (${previous.sceneId}): characters ${s.charactersPresent.join(", ")||"none"}; states ${Object.entries(s.characterStates).map(([k,v])=>`${k}=${v}`).join(", ")||"none"}; location ${s.location||"unspecified"}; time ${s.timeOfDay||"unspecified"}; weather ${s.weather||"unspecified"}; important objects ${s.importantObjects.join(", ")||"none"}; camera side ${s.cameraSide||"unspecified"}; lighting ${s.lighting||"unspecified"}; story state ${s.storyState||"unspecified"}. Preserve all unchanged facts into the next frame.`}

export function validateSceneContinuity(project:MangaProject,scene:MangaScene){const issues:ContinuityValidationIssue[]=[];for(const id of scene.characterIds){const character=project.characters.find((item)=>item.id===id);if(!character)issues.push({code:"CHARACTER_ID_MISSING",severity:"error",message:`Scene references unknown character ${id}.`,autoResolved:false});else if(!character.referencePrompt.trim())issues.push({code:"CHARACTER_CANONICAL_PROMPT_MISSING",severity:"error",message:`${character.name} has no canonical prompt.`,autoResolved:false})}if(scene.locationNames.length&&!scene.locationId)issues.push({code:"LOCATION_NOT_RESOLVED",severity:"warning",message:"Recurring location name exists but no canonical ENV id was resolved; world lock will be used.",autoResolved:true});if(scene.locationId&&!project.locations.some((item)=>item.id===scene.locationId))issues.push({code:"LOCATION_ID_MISSING",severity:"error",message:`Scene references unknown location ${scene.locationId}.`,autoResolved:false});if(!project.visualBible.masterStylePrompt.trim())issues.push({code:"MASTER_STYLE_MISSING",severity:"error",message:"Project master style prompt is empty.",autoResolved:false});if(!Number.isFinite(scene.seed)||scene.seed<=0)issues.push({code:"INVALID_SEED",severity:"error",message:"Scene seed is invalid.",autoResolved:false});return issues}

export function compileScenePrompt(input:{project:MangaProject;scene:MangaScene;previous?:SceneContinuityRecord;capabilities:ImageProviderCapabilities}){const {project,scene,previous,capabilities}=input;const bible=project.visualBible;const strength=bible.continuityStrength;const characters=scene.characterIds.map((id)=>project.characters.find((item)=>item.id===id)).filter((item):item is CharacterReference=>Boolean(item));const location=scene.locationId?project.locations.find((item)=>item.id===scene.locationId):undefined;const props=scene.propIds.map((id)=>project.props.find((item)=>item.id===id)).filter((item):item is MangaProject["props"][number]=>Boolean(item));const vehicles=scene.vehicleIds.map((id)=>project.vehicles.find((item)=>item.id===id)).filter((item):item is MangaProject["vehicles"][number]=>Boolean(item));const issues=validateSceneContinuity(project,scene);const blocks:string[]=[`MASTER STYLE LOCK:\n${bible.masterStylePrompt}`,`WORLD LOCK:\n${bible.world.canonicalPrompt}`];if(strength!=="loose"&&location)blocks.push(`LOCATION LOCK:\n${locationBlock(location)}`);if(characters.length)blocks.push(`CHARACTER LOCKS:\n${characters.map((character)=>characterBlock(character,scene.characterStates[character.name]||scene.characterStates[character.id])).join("\n")}`);if(strength==="strict"&&(props.length||vehicles.length))blocks.push(`PROP / VEHICLE LOCKS:\n${[...props,...vehicles].map(objectBlock).join("\n")}`);if(strength!=="loose"&&previous)blocks.push(previousBlock(previous));blocks.push(`CURRENT SCENE ACTION:\n${scene.action||scene.description||scene.baseImagePrompt}`);blocks.push(`CAMERA / COMPOSITION:\n${scene.shot.shotSize}; ${scene.shot.cameraAngle}; ${scene.shot.lensFeel}; composition ${scene.shot.composition}; camera movement suggestion ${scene.shot.cameraMovementSuggestion}.`);blocks.push(`LIGHTING / ATMOSPHERE:\n${scene.lightingStyle}. Time of day: ${scene.timeOfDay}. Weather: ${scene.weather}. Emotion: ${scene.emotion}.`);if(scene.baseImagePrompt.trim())blocks.push(`SCENE-SPECIFIC VISUAL NOTES:\n${scene.baseImagePrompt}`);if(strength==="strict")blocks.push(STRICT_LOCK);else if(strength==="balanced")blocks.push("CONTINUITY: preserve recurring identities, costumes, established location design and story state; allow camera and atmospheric flexibility without redesigning canon.");else blocks.push("STYLE CONTINUITY: keep the same project art direction and recognizable recurring characters while allowing greater visual variation.");const negative=bible.negativeStylePrompt.trim();if(negative&&!capabilities.negativePrompt)blocks.push(`AVOID / NEGATIVE STYLE INSTRUCTIONS:\n${negative}.`);const prompt=blocks.filter(Boolean).join("\n\n");return {prompt,negativePrompt:capabilities.negativePrompt?negative:undefined,issues,fingerprint:promptFingerprint(prompt)}}
